carpetFinder/base/urls.py
from django.urls import path
from . import views
from .forms import LoginForm
from django.contrib.auth import views as auth_views



app_name = 'base'

urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='base/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', views._logout, name='logout'),
    path('search/', views.search, name='search'),
    path('profile/', views.profile, name='profile'),
]

carpetFinder/carpetFinder/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('carpet/', include('carpet.urls')),
    path('inbox/', include('conversation.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carpetFinder/conversation/urls.py
from django.urls import path
from . import views

app_name = 'conversation'

urlpatterns = [
    path('new/<int:carpet_id>/', views.new_conversation, name='new'),
    path('', views.inbox, name='inbox'),
    path('<int:id>/', views.detail, name='detail'),
    path('delete/<int:id>/', views.delete, name='delete'),
]

carpetFinder/conversation/models.py
from django.db import models
from django.db import models
from django.contrib.auth.models import User
from carpet.models import Carpet

class Conversation(models.Model):
    carpet = models.ForeignKey(Carpet, related_name='conversations', on_delete=models.CASCADE)
    members = models.ManyToManyField(User, related_name='conversations')
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-modified_at',)


class ConversationMessage(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    conversation = models.ForeignKey(Conversation, related_name='messages', on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, related_name='messages', on_delete=models.CASCADE)

carpetFinder/conversation/forms.py
from django import forms

from .models import ConversationMessage


class ConversationMessageForm(forms.ModelForm):
    class Meta:
        model = ConversationMessage
        fields = ('content',)
        widgets = {
            'content': forms.Textarea(attrs={
            'class': 'w-full py-4 px-6 rounded-xl border'
            })
        }

carpetFinder/conversation/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from carpet.models import Carpet
from .models import Conversation
from .forms import ConversationMessageForm

@login_required
def new_conversation(request, carpet_id):
    carpet = get_object_or_404(Carpet, id=carpet_id)

    conversations = Conversation.objects.filter(carpet=carpet).filter(members__in=[request.user.id])

    if conversations:
        return redirect('conversation:detail', id=conversations.first().id)

    if request.method == 'POST':
        form = ConversationMessageForm(request.POST)
        if form.is_valid():
            conversation = Conversation.objects.create(carpet=carpet)
            conversation.members.add(request.user)
            conversation.members.add(carpet.seller)
            conversation.save()

            message = form.save(commit=False)
            message.conversation = conversation
            message.created_by = request.user
            message.save()

            return redirect('carpet:detail', carpet_id)
    else:
        form = ConversationMessageForm()

    return render(request, 'conversation/new.html', {
        'form': form
    })

@login_required
def inbox(request):
    conversations = Conversation.objects.filter(members__in=[request.user.id])
    return render(request, 'conversation/inbox.html', {
        'conversations': conversations
    })


@login_required
def detail(request, id):
    conversation = Conversation.objects.filter(members__in=[request.user.id]).get(id=id)

    if request.method == 'POST':
        form = ConversationMessageForm(request.POST)

        if form.is_valid():
            message = form.save(commit=False)
            message.conversation = conversation
            message.created_by = request.user
            message.save()

            conversation.save()

            return redirect('conversation:detail', id=id)

    else:
        form = ConversationMessageForm()
    return render(request, 'conversation/detail.html', {
        'conversation': conversation,
        'form': form
    })

@login_required
def delete(request, id):
    conversation = get_object_or_404(Conversation, id=id)
    conversation.delete()
    return redirect('conversation:inbox')

carpetFinder/conversation/templates/conversation/detail.html
{% extends 'base/home.html' %}

{% block title %}Conversation{% endblock %}

{% block content %}
<h1 class="mb-6 text-3xl">Conversation</h1>

<div class="space-y-6">
    {% for message in conversation.messages.all %}
        <div class="p-6 flex {% if message.created_by == request.user %}bg-blue-100{% else %}bg-gray-100{% endif %} rounded-xl">
            <div>
                <p class="mb-4"><strong>{{ message.created_by.username }}</strong> @ {{ message.created_at }}</p>
                <p>{{ message.content }}</p>
            </div>
            
        </div>
    {% endfor %}
</div>

<form method="post" action="." class="mt-6">
    {% csrf_token %}

    {{ form.as_p }}

    <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Send</button>
</form>
{% endblock %}

carpetFinder/conversation/templates/conversation/inbox.html
{% extends 'base/home.html' %}

{% block title %}Inbox{% endblock %}

{% block content %}
<h1 class="mb-6 text-3xl">Inbox</h1>

<div class="space-y-6">
    {% for conversation in conversations %}
        <div class="p-6 flex justify-between items-center bg-gray-100 rounded-xl">
            <a href="{% url 'conversation:detail' conversation.id %}" class="flex items-center">
                <div class="pr-6">
                    <img src="{{ conversation.carpet.image.url }}" class="w-20 rounded-xl">
                </div>
                <div>
                    {% for member in conversation.members.all %}
                        {% if member != request.user %}
                            <p class="mb-4"><strong>{{ member.username }}</strong> | {{ conversation.modified_at }}</p>
                            <p>{{ conversation.item.name }}</p>
                        {% endif %}
                    {% endfor %}
                </div>
            </a>
            <a href="{% url 'conversation:delete' conversation.id %}" class="inline-block px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl hover:bg-red-700">
                Delete
            </a>
        </div>
    {% endfor %}
</div>
{% endblock %}

carpetFinder/conversation/templates/conversation/new.html
{% extends 'base/home.html' %}

{% block title %}New conversation{% endblock %}

{% block content %}
<h1 class="mb-6 text-3xl">New conversation</h1>

<form method="post" action=".">
    {% csrf_token %}

    <div class="space-y-4">
        {{ form.as_p }}
    </div>

    {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>
    {% endif %}

    <button class="mt-6 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Send</button>
</form>
{% endblock %}