carpetFinder/base/urls.py
from django.urls import path
from . import views
from .forms import LoginForm
from django.contrib.auth import views as auth_views



app_name = 'base'

urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='base/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', views._logout, name='logout'),
    path('search/', views.search, name='search'),
    path('profile/', views.profile, name='profile'),
]

carpetFinder/carpet/urls.py
from django.urls import path
from . import views


app_name = 'carpet'

urlpatterns = [
    path('add/', views.add, name='add'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('<int:id>/', views.detail, name='detail'),
    path('<int:id>/edit/', views.edit, name='edit'),
    path('<int:id>/delete/', views.delete, name='delete'),
]

carpetFinder/carpetFinder/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('carpet/', include('carpet.urls')),
    path('inbox/', include('conversation.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carpetFinder/conversation/urls.py
from django.urls import path
from . import views

app_name = 'conversation'

urlpatterns = [
    path('new/<int:carpet_id>/', views.new_conversation, name='new'),
    path('', views.inbox, name='inbox'),
    path('<int:id>/', views.detail, name='detail'),
    path('delete/<int:id>/', views.delete, name='delete'),
]

carpetFinder/base/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
	user = models.OneToOneField(User, related_name='userProfile', null=True, blank=True, on_delete=models.CASCADE)
	profile_pic = models.ImageField(upload_to='profile_images', null=True, blank=True)

carpetFinder/base/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import UserProfile


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))



class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'phoneNumber', 'location', 'password1', 'password2',)

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email address',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    phoneNumber = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your phone number',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    location = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your location',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

carpetFinder/base/views.py
from django.shortcuts import render, redirect
from carpet.models import Carpet
from .forms import SignupForm
from django.contrib.auth import logout, login
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from .forms import LoginForm



def home(request):
    carpets = Carpet.objects.filter(is_sold=False)[0:6]
    return render(request, 'base/index.html', {
        'carpets': carpets
    })

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/login/')
    else:
        form = SignupForm()
    return render(request, 'base/signup.html', {
        'form': form
    })

def _logout(request):
    logout(request)
    return redirect('base:home')

@login_required
def search(request):
    query = request.GET.get('q', '')
    style = request.GET.get('style')
    color = request.GET.get('color')
    suitability = request.GET.get('suitability')
    carpets = Carpet.objects.filter(is_sold=False)
    if query:
        carpets = carpets.filter(Q(name__icontains=query) | Q(description__icontains=query) | Q(location__icontains=query))

    if style:
        carpets = carpets.filter(style=style)
    if color:
        carpets = carpets.filter(color=color)
    if suitability:
        carpets = carpets.filter(suitability=suitability)

    styles = [style[0] for style in Carpet.STYLE_CHOICES]
    colors = [color[0] for color in Carpet.COLOR_CHOICES]
    suitabilities = [suitability[0] for suitability in Carpet.SUITABILITY_CHOICES]

    return render(request, 'base/search.html', {
        'query': query,
        'carpets': carpets,
        'styles': styles,
        'colors': colors,
        'suitabilities': suitabilities
    })



def profile(request):
    user_profile = request.user
    return render(request, 'base/profile.html', {
        'user_profile': user_profile
    })

carpetFinder/base/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %} | CarpetFinder</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <style>
        .hero-bg {
            background-image: url('{% static "images/CARPET-BANNER-IMAGE.jpg" %}'); /* Replace with your hero image URL */
            background-size: cover;
            background-position: center;
        }
    </style>
</head>
<body class="bg-gray-100 text-gray-800">


    <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
        <a href="/" class="text-xl font-semibold">
            <span style="color: rgb(181, 101, 29);">Carpet</span><span style="color: rgb(74, 74, 74);">Finder</span>
        </a>
        <div class="flex-grow flex justify-center"> 
            {% if request.user.is_authenticated %}
            <form action="{% url 'base:search' %}" method="GET" class="flex items-center">
                <input type="text" placeholder="Type to search" name='q' class="px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:border-blue-500">
                <button type="submit" class="px-4 py-2 bg-blue-500 text-white rounded-lg ml-2 hover:bg-blue-700">Search</button>
            </form>
            {% endif %}
        </div>
        <div class="space-x-4">
            {% if request.user.is_authenticated %}
                <a href="{% url 'carpet:add' %}" class="text-lg font-semibold hover:text-gray-500">New carpet</a>
                <a href="{% url 'carpet:dashboard' %}" class="text-lg font-semibold hover:text-gray-500">Dashboard</a>
                <a href="{% url 'conversation:inbox' %}" class="text-lg font-semibold hover:text-gray-500">Inbox</a>
                <a href="{% url 'base:profile' %}" class="text-lg font-semibold hover:text-gray-500">Profile</a>
            {% else %}
                <a href="{% url 'base:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
                <a href="{% url 'base:login' %}?next={{ request.path }}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log in</a>
            {% endif %}
        </div>
    </nav>

    <section class="hero-bg h-screen flex items-center justify-center text-white">
        <div class="text-center">
            <h1 class="text-5xl font-bold mb-4">Discover the Perfect Carpet for Your Home</h1>
            <p class="text-xl mb-6">Explore a wide range of styles and colors to find your perfect match.</p>
            <a href="{% url 'base:signup' %}" class="px-6 py-3 bg-teal-500 text-white rounded-xl hover:bg-teal-700">Shop Now</a>
        </div>
    </section>

    
    <section id="products" class="py-16 bg-gray-100">
        {% block content %}
        {% endblock %}
    </section>


    <section id="about" class="py-16 bg-white text-center">
        <div class="container mx-auto">
            <h2 class="text-3xl font-bold mb-4">About CarpetFinder</h2>
            <p class="text-lg mb-6">At CarpetFinder, we offer the finest selection of carpets from around the world. Whether you're looking for modern designs or traditional patterns, we have something for every taste and budget.</p>
            <a href="#contact" class="px-6 py-3 bg-teal-500 text-white rounded-xl hover:bg-teal-700">Contact Us</a>
        </div>
    </section>

    

    <footer class="py-5 px-5 bg-gray-800 text-white text-center">
        <div class="flex justify-between">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold">About</h3>
                <p class="text-lg">CarpetFinder is a web application that helps users locate and connect with carpet sellers, providing detailed information about sellers locations and enabling seamless communication between buyers and sellers.</p>
            </div>
            <div class="w-1/3">
                <h3 class="mb-5 font-semibold">Menu</h3>
                <ul class="space-y-2">
                    <li><a href="#about" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                    <li><a href="#contact" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy Policy</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Terms of Use</a></li>
                </ul>
            </div>
        </div>
    </footer>

</body>
</html>

carpetFinder/base/templates/base/home.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %} | CarpetFinder</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <style>
        .hero-bg {
            background-image: url('{% static "images/CARPET-BANNER-IMAGE.jpg" %}'); 
            background-size: cover;
            background-position: center;
        }
    </style>
</head>
<body class="bg-gray-100 text-gray-800">

    <!-- Navbar -->
    <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
        <a href="/" class="text-xl font-semibold">
            <span style="color: rgb(181, 101, 29);">Carpet</span><span style="color: rgb(74, 74, 74);">Finder</span>
        </a>
        
        <div class="flex-grow flex justify-center"> 
            {% if request.user.is_authenticated %}
            <form action="{% url 'base:search' %}" method="GET" class="flex items-center">
                <input type="text" placeholder="Type to search" name='q' class="px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:border-blue-500">
                <button type="submit" class="px-4 py-2 bg-blue-500 text-white rounded-lg ml-2 hover:bg-blue-700">Search</button>
            </form>
            {% endif %}
        </div>
        <div class="space-x-4">
            {% if request.user.is_authenticated %}
                <a href="{% url 'carpet:add' %}" class="text-lg font-semibold hover:text-gray-500">New carpet</a>
                <a href="{% url 'carpet:dashboard' %}" class="text-lg font-semibold hover:text-gray-500">Dashboard</a>
                <a href="{% url 'conversation:inbox' %}" class="text-lg font-semibold hover:text-gray-500">Inbox</a>
                <a href="{% url 'base:profile' %}" class="text-lg font-semibold hover:text-gray-500">Profile</a>
                
                    
            {% else %}
                <a href="{% url 'base:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
                <a href="{% url 'base:login' %}?next={{ request.path }}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log in</a>
            {% endif %}
        </div>
    </nav>

    <div class="px-6 py-6">
        {% block content %}
        {% endblock %}
    </div>

    <footer class="py-5 px-5 bg-gray-800 text-white text-center">
        <div class="flex justify-between">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold">About</h3>
                <p class="text-lg">CarpetFinder is a web application that helps users locate and connect with carpet sellers, providing detailed information about sellers locations and enabling seamless communication between buyers and sellers.</p>
            </div>
            <div class="w-1/3">
                <h3 class="mb-5 font-semibold">Menu</h3>
                <ul class="space-y-2">
                    <li><a href="#about" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                    <li><a href="#contact" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy Policy</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Terms of Use</a></li>
                </ul>
            </div>
        </div>
    </footer>

</body>
</html>

carpetFinder/base/templates/base/index.html
{% extends 'base/base.html' %}

{% block title %}
    Welcome
{% endblock %}

{% block content %}
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Newest items</h2>

    <div class="grid grid-cols-3 gap-3">
        {% for carpet in carpets %}
        <div>
            <a href="{% url 'carpet:detail' carpet.id%}">
                <div>
                    <img src="{{ carpet.image.url }}" class="w-full rounded-t-xl">
                </div>

                <div class="p-6 bg-white rounded-b-xl">
                    <h2 class="text-2xl">{{ carpet.name }}</h2>
                    <p class="text-gray-500">Price: {{ carpet.price }}</p>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

carpetFinder/base/templates/base/login.html
{% extends 'base/home.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Login</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password }}
        </div>

        {% if request.GET.next %}
        <input type="hidden" name="next" value="{{ request.GET.next }}" />
        {% endif %}

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}

carpetFinder/base/templates/base/profile.html
{% extends 'base/home.html' %}

{% block title %}
    Profile
{% endblock %}

{% block content %}
   
<div class="container mx-auto my-10 p-5 flex flex-col justify-between h-screen">
    <div class="md:flex no-wrap md:-mx-2">
        <div class="w-full md:w-3/12 md:mx-2">
            <div class="bg-white p-3 border-t-4 border-green-400">
                <div class="image overflow-hidden">
                    <img class="h-auto w-full mx-auto"
                         src="{{ user_profile.profile_pic.url }}"
                         alt="User profile picture">
                </div>
                <h1 class="text-gray-900 font-bold text-xl leading-8 my-1">{{ user_profile.username }}</h1>
                <ul class="bg-gray-100 text-gray-600 mt-3 divide-y rounded shadow-sm">
                    <li class="flex items-center py-3">
                        <span>Email:</span>
                        <span class="ml-auto">{{ user_profile.email }}</span>
                    </li>
                    <li class="flex items-center py-3">
                        <span>Location:</span>
                        <span class="ml-auto">{{ user_profile.location }}</span>
                    </li>
                </ul>
            </div>
        </div>
        <div class="w-full md:w-9/12 mx-2">
            <div class="bg-white p-3 shadow-sm rounded-sm">
                <div class="flex items-center space-x-2 font-semibold text-gray-900 leading-8">
                    <span class="text-green-500">
                        <svg class="h-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
                        </svg>
                    </span>
                    <span class="tracking-wide">About</span>
                </div>
                <div class="text-gray-700">
                    <div class="grid md:grid-cols-2 text-sm">
                        <div class="grid grid-cols-2">
                            <div class="px-4 py-2 font-semibold">First Name</div>
                            <div class="px-4 py-2">{{ user_profile.first_name }}</div>
                        </div>
                        <div class="grid grid-cols-2">
                            <div class="px-4 py-2 font-semibold">Last Name</div>
                            <div class="px-4 py-2">{{ user_profile.last_name }}</div>
                        </div>
                        <div class="grid grid-cols-2">
                            <div class="px-4 py-2 font-semibold">Phone</div>
                            <div class="px-4 py-2">{{ user_profile.phone }}</div>
                        </div>
                        <div class="grid grid-cols-2">
                            <div class="px-4 py-2 font-semibold">Address</div>
                            <div class="px-4 py-2">{{ user_profile.address }}</div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="flex space-x-2 mt-4">
                <a href="#" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Edit</a>
                <form method="POST" action="#">
                    {% csrf_token %}
                    <button type="submit" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">Delete</button>
                </form>
            </div>
        </div>
    </div>
    <div class="flex justify-end">
        <a href="{% url 'base:logout' %}" class="px-4 py-2 text-lg font-semibold bg-red-500 text-white rounded-full hover:bg-gray-700">
            <i class="fa fa-power-off mr-1"></i> Log out
        </a>
    </div>
</div>


{% endblock %}

carpetFinder/base/templates/base/search.html
{% extends 'base/home.html' %}

{% block title %}carpets{% endblock %}

{% block content %}
<div class="pb-6 grid grid-cols-4 gap-4 bg-gray-100">
    <div class="col-span-1">

        <p class="font-semibold py-2 px-2">styles</p>

        <ul>
            {% for style in styles %}
                <li class="py-2 px-2 rounded-xl bg-gray-100 mt-2">
                    <a href="{% url 'base:search' %}?style={{ style }}">{{ style }}</a>
                </li>
            {% endfor %}
        </ul>

        <hr class="my-6">

        <p class="font-semibold py-2 px-2">colors</p>

        <ul>
            {% for color in colors %}
                <li class="py-2 px-2 rounded-xl bg-gray-100 mt-2">
                    <a href="{% url 'base:search' %}?color={{ color }}">{{ color }}</a>
                </li>
            {% endfor %}
        </ul>

        <hr class="my-6">

        <p class="font-semibold py-2 px-2">suitabilities</p>

        <ul>
            {% for suitability in suitabilities %}
                <li class="py-2 px-2 rounded-xl bg-gray-100 mt-2">
                    <a href="{% url 'base:search' %}?suitability={{ suitability }}">{{ suitability }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>

    <div class="col-span-3">
        <div class="grid grid-cols-3 gap-3">
            {% for carpet in carpets %}
                <div>
                    <a href="{% url 'carpet:detail' carpet.id %}">
                        <div>
                            <img src="{{ carpet.image.url }}" class="rounded-t-xl">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ carpet.name }}</h2>
                            <p class="text-gray-500">Price: {{ carpet.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

carpetFinder/base/templates/base/signup.html
{% extends 'base/home.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign up</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Email</label><br>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Phone Number</label><br>
            {{ form.phoneNumber }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Location</label><br>
            {{ form.location }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Repeat password</label><br>
            {{ form.password2 }}
        </div>

        

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}