carpetFinder/base/urls.py
from django.urls import path
from . import views
from .forms import LoginForm
from django.contrib.auth import views as auth_views



app_name = 'base'

urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='base/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', views._logout, name='logout'),
    path('search/', views.search, name='search'),
    path('profile/', views.profile, name='profile'),
]

carpetFinder/carpet/urls.py
from django.urls import path
from . import views


app_name = 'carpet'

urlpatterns = [
    path('add/', views.add, name='add'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('<int:id>/', views.detail, name='detail'),
    path('<int:id>/edit/', views.edit, name='edit'),
    path('<int:id>/delete/', views.delete, name='delete'),
]

carpetFinder/carpetFinder/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('carpet/', include('carpet.urls')),
    path('inbox/', include('conversation.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carpetFinder/conversation/urls.py
from django.urls import path
from . import views

app_name = 'conversation'

urlpatterns = [
    path('new/<int:carpet_id>/', views.new_conversation, name='new'),
    path('', views.inbox, name='inbox'),
    path('<int:id>/', views.detail, name='detail'),
    path('delete/<int:id>/', views.delete, name='delete'),
]

carpetFinder/carpet/models.py
from django.db import models
from django.contrib.auth.models import User

class Carpet(models.Model):
    STYLE_CHOICES = [
        ('herringbone', 'Herringbone'),
        ('saxony', 'Saxony'),
        ('twist', 'Twist'),
        ('woven', 'Woven'),
        ('velvet', 'Velvet'),
    ]

    COLOR_CHOICES = [
        ('red', 'Red'),
        ('blue', 'Blue'),
        ('green', 'Green'),
        ('yellow', 'Yellow'),
        ('purple', 'Purple'),
        ('pink', 'Pink'),
        ('brown', 'Brown'),
        ('gray', 'Gray'),
        ('black', 'Black'),
        ('white', 'White'),
    ]

    SUITABILITY_CHOICES = [
        ('living_room', 'Living Room'),
        ('bedroom', 'Bedroom'),
        ('dining_room', 'Dining Room'),
        ('bathroom', 'Bathroom'),
        ('hallway', 'Hallway'),
    ]

    seller = models.ForeignKey(User, on_delete=models.CASCADE, related_name='carpets')
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    size = models.CharField(max_length=50)
    material = models.CharField(max_length=50, null=True, blank=True)
    style = models.CharField(max_length=20, choices=STYLE_CHOICES)
    color = models.CharField(max_length=20, choices=COLOR_CHOICES)
    suitability = models.CharField(max_length=20, choices=SUITABILITY_CHOICES)
    image = models.ImageField(upload_to='carpet_images', blank=True)
    is_sold = models.BooleanField(default=False)
    location = models.CharField(max_length=100, default='algeria')

    def __str__(self):
        return self.name

carpetFinder/carpet/forms.py
from django import forms

from .models import Carpet

style = 'w-full py-4 px-6 rounded-xl border'

class NewCarpetForm(forms.ModelForm):
    class Meta:
        model = Carpet
        fields = ('name', 'description', 'price', 'size', 'material', 'style', 'color', 'suitability', 'image', 'location')
        widgets = {
            'name': forms.TextInput(attrs={
                'class': style
            }),
            'description': forms.Textarea(attrs={
                'class': style
            }),
            'price': forms.TextInput(attrs={
                'class': style
            }),
            'style': forms.Select(attrs={
                'class': style
            }),
            'color': forms.Select(attrs={
                'class': style
            }),
            'suitability': forms.Select(attrs={
                'class': style
            }),
            'material': forms.Textarea(attrs= {
                'class': style
            }),
            'image': forms.FileInput(attrs={
                'class': style
            }),
            'location': forms.TextInput(attrs={
                'class': style
            }),
        }

class EditCarpetForm(forms.ModelForm):
    class Meta:
        model = Carpet
        fields = ('name', 'description', 'price', 'size', 'material', 'style', 'color', 'suitability', 'image', 'is_sold', 'location')
        widgets = {
            'name': forms.TextInput(attrs={
                'class': style
            }),
            'description': forms.Textarea(attrs={
                'class': style
            }),
            'price': forms.TextInput(attrs={
                'class': style
            }),
            'style': forms.Select(attrs={
                'class': style
            }),
            'color': forms.Select(attrs={
                'class': style
            }),
            'suitability': forms.Select(attrs={
                'class': style
            }),
            'material': forms.Textarea(attrs= {
                'class': style
            }),
            'image': forms.FileInput(attrs={
                'class': style
            }),
            'location': forms.TextInput(attrs={
                'class': style
            }),
        }

carpetFinder/carpet/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Carpet
from .forms import NewCarpetForm, EditCarpetForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required

@login_required
def add(request):
    if request.method == 'POST':
        form = NewCarpetForm(request.POST, request.FILES)

        if form.is_valid():
            carpet = form.save(commit=False)
            carpet.seller = request.user
            carpet.save()

            return redirect('carpet:detail', id=carpet.id)
    else:
        form = NewCarpetForm()

    return render(request, 'carpet/add.html', {
        'form': form,
        'title': 'New carpet'
    })

@login_required
def edit(request, id):
    carpet = get_object_or_404(Carpet, id=id, seller=request.user)

    if request.method == 'POST':
        form = EditCarpetForm(request.POST, request.FILES, instance=carpet)

        if form.is_valid():
            form.save()

            return redirect('carpet:detail', id=carpet.id)
    else:
        form = EditCarpetForm(instance=carpet)

    return render(request, 'carpet/add.html', {
        'form': form,
        'title': 'Edit carpet'
    })

@login_required
def delete(request, id):
    carpet = get_object_or_404(Carpet, id=id, seller=request.user)
    carpet.delete()
    return redirect('base:home')

@login_required
def dashboard(request):
    carpets = Carpet.objects.filter(seller=request.user)
    return render(request, 'carpet/dashboard.html', {
        'carpets': carpets,
})

@login_required
def detail(request, id):
    carpet = get_object_or_404(Carpet, id=id)
    related_carpets = Carpet.objects.filter(style=carpet.style, is_sold=False).exclude(id=id)[0:3]
    return render(request, 'carpet/detail.html', {
        'carpet': carpet,
        'related_carpets': related_carpets
    })

carpetFinder/carpet/templates/carpet/add.html
{% extends 'base/home.html' %}

{% block title %} {{ title }} {% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">{{ title }}</h1>

    <form method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}

        <div class="space-y-4">
            {{ form.as_p }}
        </div>


        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}

carpetFinder/carpet/templates/carpet/dashboard.html
{% extends 'base/home.html' %}

{% block title %}
    Dashboard
{% endblock %}

{% block content %}
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">My carpets</h2>

    <div class="grid grid-cols-3 gap-3">
        {% for carpet in carpets %}
        <div>
            <a href="{% url 'carpet:detail' carpet.id%}">
                <div>
                    <img src="{{ carpet.image.url }}" class="w-full rounded-t-xl">
                </div>

                <div class="p-6 bg-white rounded-b-xl">
                    <h2 class="text-2xl">{{ carpet.name }}</h2>
                    <p class="text-gray-500">Price: {{ carpet.price }}</p>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

carpetFinder/carpet/templates/carpet/detail.html
{% extends 'base/home.html' %}

{% block title%} {{ carpet.name }} {% endblock%}

{% block content %}
    <div class="grid grid-cols-5 gap-6">
        <div class="col-span-3">
            <img src="{{ carpet.image.url }}" class="w-full h-auto rounded-xl">
        </div>

        <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
            <h1 class="mb-6 text-3xl">{{ carpet.name }}</h1>
            <p class="text-gray-500"><strong>Price: </strong>{{ carpet.price }}</p>
            <p class="text-gray-500"><strong>Seller: </strong>{{ carpet.seller.username }}</p>
            <p class="text-gray-500"><strong>Size: </strong>{{ carpet.size}}</p>
            <p class="text-gray-500"><strong>Style: </strong>{{ carpet.style }}</p>
            <p class="text-gray-500"><strong>Color: </strong>{{ carpet.color }}</p>
            <p class="text-gray-500"><strong>Suitability: </strong>{{ carpet.suitability }}</p>
            <p class="text-gray-500"><strong>Location: </strong>{{ carpet.location }}</p>


            {% if carpet.material %}
                <p class="text-gray-700">
                    <strong class="text-gray-500">Material:</strong><br>
                    {{ carpet.material }}
                </p>
            {% endif %}
        
        
            {% if carpet.description %}
                <p class="text-gray-700">
                    <strong class="text-gray-500">Description:</strong><br>
                    {{ carpet.description }}
                </p>
            {% endif %}

            {% if request.user == carpet.seller%}
                <div class="mt-6 p-6 bg-white rounded-xl">
                    <p>This is your carpet!</p>

                    <a href="{% url 'carpet:edit' carpet.id%}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl">Edit</a>
                    <a href="{% url 'carpet:delete' carpet.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl">Delete</a>
                </div>
            {% else %}
                <a href="{% url 'conversation:new' carpet.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Contact seller</a>
            {% endif %}
            </div>
    </div>

    {% if related_carpets %}
        <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
            <h2 class="mb-12 text-2xl text-center">Related carpets</h2>
        
            <div class="grid grid-cols-3 gap-3">
                {% for carpet in related_carpets %}
                    <div>
                        <a href="{% url 'carpet:detail' carpet.id %}">
                            <div>
                                <img src="{{ carpet.image.url }}" class="w-full rounded-t-xl">
                            </div>
        
                            <div class="p-6 bg-white rounded-b-xl">
                                <h2 class="text-2xl">{{ carpet.name }}</h2>
                                <p class="text-gray-500">Price: {{ carpet.price }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}
{% endblock%}